name: Verifica칞칚o Di치ria de Alertas de Seguran칞a

on:
  schedule:
    - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  check-for-alerts:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      security-events: read

    steps:
      - name: Verificar Alertas do Dependabot via API
        id: get_alerts
        run: |
          alerts=$(gh api "repos/${{ github.repository }}/dependabot/alerts?state=open" --jq '[.[] | {number, state, severity: .security_vulnerability.severity, package: .dependency.package.name, url: .html_url}]')
          echo "ALERTS_JSON=$alerts" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.ACTION_PAT }}

      - name: Formatar Alertas para o Slack
        id: format_alerts
        if: steps.get_alerts.outputs.ALERTS_JSON != '[]' && steps.get_alerts.outputs.ALERTS_JSON != ''
        run: |
          FORMATTED_ALERTS=$(jq -r '
            .[] | "- *Pacote:* `\(.package)`\n  - *Severidade:* *\(.severity)*\n  - *Estado:* `\(.state)`\n  - *URL:* <\(.url)|\(.url)>"' <<EOF
          ${{ steps.get_alerts.outputs.ALERTS_JSON }}
          EOF
          )
          echo "FORMATTED_ALERTS<<EOF" >> $GITHUB_OUTPUT
          echo "$FORMATTED_ALERTS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Enviar Notifica칞칚o para o Slack
        if: steps.get_alerts.outputs.ALERTS_JSON != '[]' && steps.get_alerts.outputs.ALERTS_JSON != ''
        uses: cabraldasilvac/security-alert-notifier-action@main
        with:
          slack-channel-id: "C099V8S4GDD"
          slack-message: |
            游닉 *Resumo Di치rio de Alertas de Seguran칞a Abertos*
            *Reposit칩rio:* ${{ github.repository }}
            *Alertas Encontrados:*
            ${{ steps.format_alerts.outputs.FORMATTED_ALERTS }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Confirmar que n칚o h치 alertas
        if: steps.get_alerts.outputs.ALERTS_JSON == '[]' || steps.get_alerts.outputs.ALERTS_JSON == ''
        run: echo "Nenhum alerta do Dependabot encontrado. Tudo certo!"
